name: Firebase Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Login to Firebase
        run: firebase login --no-interactive --ci

      - name: Build and Deploy
        run: |
          npm install
          firebase deploy --only hosting --token $FIREBASE_TOKEN

